sonar.host.url=https://sonarqube.andersencorp.com
sonar.projectKey=edm-aw-website
sonar.projectName=Enterprise Digital Marketing - AW - Website
sonar.sources=./src
sonar.tests=./src
sonar.test.inclusions=**/*.test.ts,**/*.stories.ts
sonar.testExecutionReportPaths=test-results/sonarqube.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
