export const StringConstants = {
  AW: {
    Common: {
      ActiveJourneyKeyPrefix: 'awActiveJourney-',
    },
    DesignTool: {
      JourneyName: 'design-tool',
      ActiveJourneyKey: 'awActiveJourney-design-tool',
      StartEventType: 'AW:DESIGN_TOOL_START',
      UpdateEventType: 'AW:DESIGN_TOOL_UPDATE',
      AbandonEventType: 'AW:DESIGN_TOOL_ABANDON',
      RAQClickEventType: 'AW:DESIGN_TOOL_REQUEST_QUOTE_CLICK',
      DesignStartedKey: 'awDTDesignStarted',
      GlassReachedKey: 'awDTGlassReached',
      FromExperienceKey: 'awDTFromExperience',
      ExperienceIdKey: 'awDTExperienceId',
      AbandonPayloadKey: 'awDTAbandonPayload',
      AbandonEventTriggered: 'awDTAbandonEventTriggered',
    },
    WTB: {
      JourneyName: 'where-to-buy',
      ActiveJourneyKey: 'awActiveJourney-where-to-buy',
      MapPopupOpenEventType: 'AW:WTB_MAP_POPUP_OPEN',
      ContactClickEventType: 'AW:WTB_POPUP_CONTACT_CLICK',
      AbandonEventType: 'AW:WTB_ABANDON',
      AbandonPayloadKey: 'awWTBAbandonPayload',
      ContactClickedKey: 'awWTBContactClicked',
      AbandonEventTriggered: 'awWTBAbandonEventTriggered',
    },
    RequestQuote: {
      JourneyName: 'request-a-quote',
      ActiveJourneyKey: 'awActiveJourney-request-a-quote',
      StartEventType: 'AW:FORM_RAQ_START',
      StepCompleteEventType: 'AW:FORM_RAQ_STEP_COMPLETE',
      SubmitEventType: 'AW:FORM_RAQ_SUBMIT',
      AbandonEventType: 'AW:FORM_RAQ_ABANDON',
      AbandonPayloadKey: 'awRAQAbandonPayload',
      AbandonEventTriggered: 'awRAQAbandonEventTriggered',
      StartTimeKey: 'awRAQStartTime',
      SubmittedKey: 'awRAQSubmitted',
      FromExperienceKey: 'awRAQFromExperience',
      ExperienceIdKey: 'awRAQExperienceId',
    },
    GFBForm: {
      JourneyName: 'gfb-form',
      ActiveJourneyKey: 'awActiveJourney-gfb-form',
      AbandonEventTriggered: 'awGFBAbandonEventTriggered',
      AbandonPayloadKey: 'awGFBAbandonPayload',
    },
  },
  Enterprise: {},
};
