import { debug, GraphQLRequestClient } from '@sitecore-content-sdk/core';
import { SiteInfo } from '@sitecore-content-sdk/nextjs';
import { createGraphQLClientFactory } from '@sitecore-content-sdk/nextjs/client';
import { SitecoreConfig } from '@sitecore-content-sdk/nextjs/config';
import chalk from 'chalk';
import fs from 'fs';
import path from 'path';

const DEFAULT_OUTPUT_PATH = '.sitecore/';

/**
 * Configuration object for generating site info.
 */
export type GenerateSiteInfoConfig = {
  /**
   * Name of the generated types file.
   */
  generatedFile: string;

  /**
   * Optional path where the generated types will be saved.
   * If not provided, the default '.sitecore/' will be used.
   */
  destinationPath?: string;
};

type BuildContext = { scConfig: SitecoreConfig };

export const generateSiteInfo = ({
  // scConfig,
  generatedFile,
  destinationPath,
}: GenerateSiteInfoConfig): ((ctx: BuildContext) => Promise<void>) => {
  return async ({ scConfig }: BuildContext) => {
    const outputPath = path.resolve(destinationPath ?? DEFAULT_OUTPUT_PATH, generatedFile);

    let sites: SiteInfo[] = [];
    console.log('Fetching site information');
    try {
      const factory = createGraphQLClientFactory({
        api: scConfig.api,
        retries: scConfig.retries.count,
        retryStrategy: scConfig.retries.retryStrategy,
      });
      const client = factory({
        debugger: debug.common,
      });

      sites = await fetchSites(client);
    } catch (error) {
      console.error(chalk.red('Error fetching site information'));
      console.error(error);
    }
    writeSites(sites, outputPath);
  };
};

const siteQuery = /* GraphQL */ `
  {
    site {
      allSiteInfo {
        results {
          name
          language
          hostname
          rootPath
          attributes {
            key
            value
          }
        }
      }
    }
  }
`;

const countQuery = /* GraphQL */ `
  {
    site {
      allSiteInfo {
        total
      }
    }
  }
`;

type SiteInfoResponse = {
  site: {
    allSiteInfo: {
      results: {
        name: string;
        language: string;
        hostname: string;
        rootPath: string;
        attributes: {
          key: string;
          value: string;
        }[];
      }[];
    };
  };
};

type CountResponse = {
  site: {
    allSiteInfo: {
      total: number;
    };
  };
};

async function fetchSites(client: GraphQLRequestClient): Promise<SiteInfo[]> {
  const pageSize = 500;
  const countResponse = await client.request<CountResponse>(countQuery);
  const total = countResponse.site.allSiteInfo.total;

  const totalPages = Math.ceil(total / pageSize);

  const sites: SiteInfo[] = [];
  let pageNumber = 0;
  while (pageNumber < totalPages) {
    const siteResponse = await client.request<SiteInfoResponse>(siteQuery, {
      pageSize,
      pageNumber,
    });

    siteResponse.site.allSiteInfo.results.forEach((site) => {
      if (site.name === 'website') {
        return;
      }

      const attributes: [string, string][] = [];
      site.attributes.forEach((kv) => {
        if (kv.key === 'targetHostName') {
          attributes.push([kv.key, kv.value]);
        } else if (kv.key.startsWith('public_')) {
          const key = kv.key.substring(7);
          attributes.push([key, kv.value]);
        }
      });
      sites.push({
        name: site.name,
        hostName: site.hostname,
        language: site.language,
        rootPath: site.rootPath,
        ...Object.fromEntries(attributes),
      });
    });

    pageNumber = pageNumber + 1;
  }

  sites.push({
    name: process.env.NEXT_PUBLIC_DEFAULT_SITE_NAME ?? 'AndersenWindows',
    language: process.env.NEXT_PUBLIC_DEFAULT_LANGUAGE ?? 'en',
    hostName: '*',
  });

  return sites;
}

/**
 * Writes the sites object to disk.
 * @param {SiteInfo[]} sites sites to write.
 * @param {string} outputPath path to write the sites file to.
 */
function writeSites(sites: SiteInfo[], outputPath: string): void {
  let fileText = `/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.

import { SiteInfo } from '@sitecore-content-sdk/nextjs';

export const sites: SiteInfo[] = [`;

  sites.forEach((site) => {
    fileText += `${JSON.stringify(site, null, 2)},`;
  });

  fileText += `\n];\n`;

  console.log(`Writing sites to ${outputPath}`);
  fs.writeFileSync(outputPath, fileText, { encoding: 'utf8' });
}
