export enum QueryNodeOperator {
  Equal = '=',
  ExactMatch = '==',
  NotEqual = '<>',
  WildcardMatch = '*=',
  LessThan = '<',
  GreaterThan = '>',
  LessThanOrEqual = '<=',
  GreaterThanOrEqual = '>=',
  EmptyField = 'emptyField*',
  EmptyFieldValue = 'emptyValue*',
  Range = '..',
  FuzzyMatch = '~=',
  RegexMatch = '/=',
  PhoneticMatch = '%=',
  Unknown = '',
}
