/**
 * Describes a file that represents a component definition
 */
export interface ComponentServerPropsProviderObjectFile {
  path: string;
  fieldName: string;
}

/**
 * Generates the contents of the component factory file using a predefined string template.
 * @param components - the list of component files to include
 * @returns component factory file contents
 */
function buildFactory(items: Array<ComponentServerPropsProviderObjectFile>): string {
  return `/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See tools/form/generate-component-server-props-provider-factory.ts to modify the generation of this file.
import { ComponentRendering } from '@sitecore-content-sdk/nextjs';

${items
  .map((item) => {
    return `import { getComponentServerProps as ${item.fieldName} } from '${item.path}';`;
  })
  .join('\n')}

type ComponentServerPropsProvider = (rendering: ComponentRendering) => Promise<unknown>;

const map = new Map<string, ComponentServerPropsProvider>();
${items
  .map((item) => {
    return `map.set('${item.fieldName}', ${item.fieldName})`;
  })
  .join('\n')}

export function componentServerPropsProviderFactory(
  componentName: string
): ComponentServerPropsProvider | undefined {
  const provider = map.get(componentName);

  return provider;
}
`;
}

export default buildFactory;
