/**
 * Describes a file that represents a component definition
 */
export interface FormItemDetailProviderObjectFile {
  path: string;
  fieldName: string;
}

/**
 * Generates the contents of the component factory file using a predefined string template.
 * @param components - the list of component files to include
 * @returns component factory file contents
 */
function buildFactory(items: Array<FormItemDetailProviderObjectFile>): string {
  return `/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See tools/form/generate-form-item-detail-provider-factory.ts to modify the generation of this file.


${items
  .map((item) => {
    return `import { getFormItemDetail as ${item.fieldName} } from '${item.path}';`;
  })
  .join('\n')}

import { FormItemDetail } from 'src/lib/generic-form-builder/utils/load-utils/form-item-detail';

type FormItemDetailProvider<T> = (props: T) => Promise<FormItemDetail | undefined>;

const map = new Map<string, FormItemDetailProvider<unknown>>();
${items
  .map((item) => {
    return `map.set('${item.fieldName}', ${item.fieldName})`;
  })
  .join('\n')}

  export function formItemDetailProviderFactory<T = unknown>(
  componentName: string
): FormItemDetailProvider<T> | undefined {
  const provider = map.get(componentName);

  return provider;
}
`;
}

export default buildFactory;
