/**
 * Describes a file that represents a component definition
 */
export interface FormPageDetailProviderObjectFile {
  path: string;
  fieldName: string;
}

/**
 * Generates the contents of the component factory file using a predefined string template.
 * @param components - the list of component files to include
 * @returns component factory file contents
 */
function buildFactory(items: Array<FormPageDetailProviderObjectFile>): string {
  return `/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See tools/form/generate-form-page-detail-provider-factory.ts to modify the generation of this file.


${items
  .map((item) => {
    return `import { getFormPageDetail as ${item.fieldName} } from '${item.path}';`;
  })
  .join('\n')}

import { FormPageDetail } from 'src/lib/generic-form-builder/utils/load-utils/form-page-detail';

type FormPageDetailProvider<T> = (props: T) => Promise<FormPageDetail | undefined>;

const map = new Map<string, FormPageDetailProvider<unknown>>();
${items
  .map((item) => {
    return `map.set('${item.fieldName}', ${item.fieldName})`;
  })
  .join('\n')}

  export function formPageDetailProviderFactory<T = unknown>(
  componentName: string
): FormPageDetailProvider<T> | undefined {
  const provider = map.get(componentName);

  return provider;
}
`;
}

export default buildFactory;
